# Configuration Netlify
[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

# Variables d'environnement pour la production
[build.environment]
  NODE_VERSION = "16"
  AWS_LAMBDA_JS_RUNTIME = "nodejs16.x"
  AWS_REGION = "eu-north-1"

# Ajout d'une règle spécifique pour les fichiers statiques (priorité la plus élevée)
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Redirections pour les fonctions de tracking
[[redirects]]
  from = "/track/p/*"
  to = "/.netlify/functions/tracking-pixel"
  status = 200
  force = true

[[redirects]]
  from = "/track/r/*"
  to = "/.netlify/functions/link-redirect"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhook/bounce"
  to = "/.netlify/functions/bounce-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhook/delivery"
  to = "/.netlify/functions/delivery-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhook/aws-ses"
  to = "/.netlify/functions/aws-ses-webhook"
  status = 200
  force = true

# Gestion des routes SPA (Single Page Application) - doit être en dernier
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000 