# Configuration Netlify
[build]
  command = "CI=false npm run build"
  publish = "build"

# Gestion des routes SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[build.environment]
  REACT_APP_AWS_REGION = "us-east-1"
  REACT_APP_AWS_USER_POOL_ID = "us-east-1_MruE6Kyew"
  REACT_APP_AWS_APP_CLIENT_ID = "37di4rkduiuhvhc2jos507qsdl"